# Generated by Django 3.0.4 on 2020-03-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainting',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idk.Movie', verbose_name='фильм'),
        ),
    ]
